### PR TITLE
MNT: rerender

### LINKED ISSUE #36: @conda-forge-admin please rerender
@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #36.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #36

### CODE REVIEW

**Comment by bam241** [comment]
@conda-forge-admin please rerender

**Comment by scopatz** [comment]
cyclus-build-deps has a conflict with Python v3.7

**Comment by bam241** [comment]
@scopatz Yes I fixed it in [cyclus-build-deps#22](https://github.com/conda-forge/cyclus-build-deps-feedstock/pull/22)

**Comment by bam241** [comment]
@conda-forge-admin please rerender

**Comment by bam241** [comment]
@conda-forge-admin please rerender

**Pull request closed without merging**
