### PR TITLE
changing cython limitation and remove python warning for nosetests

### PR DESCRIPTION
**Pull request by bam241**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

this should allow to have a python version up to 0.28.x

### CODE REVIEW

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
wow this worked on 3.6!

**Comment by bam241** [comment]
This is because of a file name conflict between python 3.7 and Cyclus...

I have a fix PRed on Cyclus.... I forgot I need a new version...

**Pull request closed without merging**
