### PR TITLE
abandon python 3.9.x and lower

### PR DESCRIPTION
**Pull request by gonuke**
Based on an attempt to autoupdate to HDF5 1.14.4 in #91, I learned that pytables is unlikely to ever be available with Python 3.9 and HDF5 1.14.4.  Based on this this PR removes conda support for python < 3.10 (conda-forge/pytables-feedstock#102)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gonuke** [comment]
@conda-forge-admin, please rerender

**Comment by bennibbelink** [comment]
I think the changes in this PR were included in #100, @gonuke feel free to close this if that is correct.

**Comment by gonuke** [comment]
This one propagates those changes to the `dev` branch, but let me know if you want to pull them in in some other way

**Comment by bennibbelink** [comment]
Got it, LGTM. Thanks @gonuke!

**Pull request merged**
