### PR TITLE
Recipe updates for cyclus release. 

### PR DESCRIPTION
**Pull request by munkm**
I'm going to update the recipe slowly and see how well things go. This shouldn't be merged until we have a version and SHA we can reference in `meta.yaml` for the new version. 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by munkm** [comment]
@gonuke do we still need all of the flags (like https://github.com/conda-forge/cyclus-feedstock/blob/main/recipe/build.sh#L19) in the `build.sh` file? @bennibbelink says the default is now to build without coin so this flag seems a little redundant?

**Comment by gonuke** [comment]
Maybe we need to review when/if we build with/out COIN.  I thought we did build with COIN in our CI builds.

**Comment by gonuke** [comment]
Or maybe I misunderstood this comment.... Since we are building with conda successfully in CI, I would recommend we use the same flags as the CI build in the Dockerfile... unless we think we want to deliver a different configuration for conda-forge?

**Comment by munkm** [comment]
> I would recommend we use the same flags as the CI build in the Dockerfile... unless we think we want to deliver a different configuration for conda-forge? 

It sounds reasonable to me to try to replicate what we have that's already successful. I can't currently think of a use case where we'd want a different option here than in the dockerfile.

**Comment by munkm** [comment]
Closing this in favor of https://github.com/conda-forge/cyclus-feedstock/pull/75

**Pull request closed without merging**
