### PR TITLE
rebuild for upstream changes

### PR DESCRIPTION
**Pull request by bennibbelink**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Just a simple build increment to rebuild this package with the latest changes from `cyclus/cyclus`

### CODE REVIEW

**Comment by gonuke** [comment]
It looks like this was just testing the automation you were trying.  I'm happy to merge it, but I'm not sure if it's necessary....

**Comment by bennibbelink** [comment]
This was manual by me actually, sorry I should've been more clear in the PR description.  I wanted to rebuild the package to include the recent locale changes.

**Comment by gonuke** [comment]
If you update with changes from #100, I'll go ahead and merge

**Comment by gonuke** [comment]
Or maybe #100 accomplished the rebuild you were after, so this is superfluous?

**Comment by bennibbelink** [comment]
Closing this, #100 rebuilt the `cyclus_dev` package with the desired changes.

**Pull request closed without merging**
