### PR TITLE
try to build cyclus for Python 3.6

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a re-render too. Though may need to manually save the long prefix/conda-build 2 bits so the re-rendering doesn't wipe them out.

**Comment by scopatz** [comment]
Yeah, I tried a rerender, but the only things it changed where exactly the conda-build v2 changes you pointed out needed to be kept.

**Comment by scopatz** [comment]
Ok, so this is weird, even when I rerender, it doesn't add the Python 3.6 parts. Is there something I am missing here?

**Comment by scopatz** [comment]
Is that something I have to add manually?

**Comment by scopatz** [comment]
Ok, I'll try to hunt it down, then.

**Comment by scopatz** [comment]
Oh shoot maybe it is boost.

**Pull request merged**
