### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jjhelmus can you try navigating to https://circleci.com/gh/jjhelmus/cyclus-feedstock and cliking on follow the project? That should get `CircleCi` going here.

**Comment by jjhelmus** [comment]
I followed the project but it did not seem to kick off a build.

**Comment by jjhelmus** [comment]
I'm going to try the follow project idea on one other feedstock to see if it works.

**Comment by ocefpaf** [comment]
I see it here: https://circleci.com/gh/jjhelmus/cyclus-feedstock/2

**Comment by jjhelmus** [comment]
> I see it here: https://circleci.com/gh/jjhelmus/cyclus-feedstock/2

I manually started that one and it is of the `master` branch not the pull request :cry:

**Comment by ocefpaf** [comment]
> I manually started that one and it is of the `master` branch not the pull request :cry: 

Argh... It did work for me in another project. Maybe you need to send another "commit" to trigger it. Not sure.

**Comment by jjhelmus** [comment]
> Maybe you need to send another "commit" to trigger it. Not sure.

Yes, that seems to have done the trick in conda-forge/ecmwf_grib-feedstock#20.  Not idea but at least it provides a workflow.

**Comment by scopatz** [comment]
Hey All, Please PR into #13 for the new version. I have opened gonuke/cyclus-feedstock#1 that includes the changes here, BTW.  Or you can keep pushing here and then and I can worry about resolving conflicts. Just let me know when you do, please. Thanks!

**Comment by jjhelmus** [comment]
@scopatz Happy to close this in favor of #13, as long as a long prefix build of the new version is available.  

Once this is done [cycamore](https://github.com/conda-forge/cycamore-feedstock/) will also need to be rebuild with a long prefix. This could be done in conda-forge/cycamore-feedstock#5 using the same workflow as was done here.  

More details on the whole update to `conda-build` 2 can be found in conda-forge/conda-forge-build-setup-feedstock#40.

**Comment by scopatz** [comment]
Thanks @jjhelmus!

**Pull request closed without merging**
