### PR TITLE
Update for v1.5.0 release

### PR DESCRIPTION
**Pull request by gonuke**
This should be everything required:
* updated the version
* updated the sha256 to match the current archive of `master`
* added dependencies: cython, numpy, pandas (not sure what versions matter?)

Curious: why pull the tarball from `master` rather than the release?

### CODE REVIEW

**Comment by gonuke** [comment]
I just reset the build counter to 0 - hope that's correct.

**Comment by scopatz** [comment]
BTW I just canceld some of CI jobs for the older hashes, so we don't waste time in the queue.

**Comment by gonuke** [comment]
:+1: not sure if I know how to do that...
Also - regarding the fact that we pull the 'master' tarball... isn't it cleaner to pull the release tarball?  I noticed that a previous PR failed because the SHA changed as `master` was updated

**Comment by scopatz** [comment]
> :+1: not sure if I know how to do that...

Yeah you have to go into Travis to do that.

> Also - regarding the fact that we pull the 'master' tarball... isn't it cleaner to pull the release tarball? I noticed that a previous PR failed because the SHA changed as master was updated

Yeah, probably. We really should switch it to pulling the release tag tarball. I had just done this for testing. The "branch" name is somewhat of a misnomer since it can also be a tag.

**Comment by scopatz** [comment]
We can probably hold off on that for the moment, though. It is best to get something working :)

**Comment by scopatz** [comment]
Ok, so this works for me on linux with the docker. All that we need is for travis to build mac

**Comment by Baaaaam** [comment]
On the README of gonuke/cyclus-feedstock in the current release info, the version number is `1.4.0`, will it automatically be updated ?

**Comment by scopatz** [comment]
@Baaaaam - We can rerender later, which will fix all of the autogenerated pieces like that.

**Comment by gonuke** [comment]
Doesn't this update automatically once this PR is merged and the rendered package is logged with conda?

**Comment by gonuke** [comment]
This seemed to fail on a single of the 4 configurations, and due to a timeout.  Can we relaunch somehow?

**Comment by scopatz** [comment]
> Doesn't this update automatically once this PR is merged and the rendered package is logged with conda?

Sorry, this is a bit confusing. Rerendering is a verb that applies to the recipe repo, not the package. The recipe (which includes the readme) is only rerendered whenever conda-smithy is updated. The package, however, is uploaded after the merge.

> This seemed to fail on a single of the 4 configurations, and due to a timeout. Can we relaunch somehow?

Yep! You can click on the Travis details and then follow that to the broken job. At the top of the job page there is a restart button.  I have already restarted it, though, so no worries.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
